name: Setup Project Template

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  setup-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Repository Name
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Replace Template Name in Files
        run: |
          find . -type f -exec sed -i "s/template_connector/${REPO_NAME}/g" {} +

      - name: Update pom.xml
        run: |
          sed -i "s/<artifactId>template_connector<\/artifactId>/<artifactId>${REPO_NAME}<\/artifactId>/g" pom.xml
          sed -i "s/<name>template_connector<\/name>/<name>${REPO_NAME}<\/name>/g" pom.xml

      - name: Rename Java Package Directories
        run: |
          OLD_PACKAGE_DIR="src/main/java/com/example/template_connector"
          NEW_PACKAGE_DIR="src/main/java/com/example/${REPO_NAME}"

          if [ "$REPO_NAME" != "template_connector" ] && [ -d "$OLD_PACKAGE_DIR" ]; then
            mkdir -p "$NEW_PACKAGE_DIR"
            mv "$OLD_PACKAGE_DIR"/* "$NEW_PACKAGE_DIR/"
            rm -rf "$OLD_PACKAGE_DIR"
          fi

      - name: Update Java Package Names in Files
        run: |
          OLD_PACKAGE="com.example.template_connector"
          NEW_PACKAGE="com.example.${REPO_NAME}"
          find src/ -type f -name "*.java" -exec sed -i "s/$OLD_PACKAGE/$NEW_PACKAGE/g" {} +

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Customized project with repository name: $REPO_NAME" || echo "No changes to commit"
          git pull --rebase
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main

      - name: Run Tests
        run: mvn test
